### ISSUE TITLE
The future of WoWs Info

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/WoWs-Info-Re#22]
# Future updates for WoWs Info
WoWs Info has reached its stable stage. The main focus now is to improve user experience. I will make some videos on how to use some wows info features and also maybe get more users (more revenue). 

I am really upset since my Admob account got banned. WoWs Info will be free forever because it should be. I had a Pro version for IOS two years ago and I have admitted that it worked really well but I removed it because I feel bad for my users. I am adding it back again this time. Ads will be removed, recent data and realtime statistics will be unlocked when you purchase the pro version.
Without pro version, it will be hard to add all these features.

I am considering rewriting the entire app in typescript or just use more design patterns. UI won't have any changes but the code will be refactored.

## Upcoming changes
- [ ] Better RS (#17)
- [ ] Support Chinese server (#21)
- [x] Better Android navigation (#19)
- [ ] Improve UWP (win10) version (#12)
- [ ] New UI, mainly home page (#24)
- [ ] Better charts
- [ ] Add CV info
- [ ] Support Mac OS
- [ ] Detail comparison with new data from API
- [ ] Add recent data for main account
- [ ] Better logo (round icon for Android)
- [ ] Logo redesign
- [ ] Better tablet support (for bigger screens)
- [ ] Better about page (What's new)
- [ ] Change loading screen theme colour according to time and server
- [ ] Add subscriptions (It takes time and effort to maintain my apps)

## Bug fixes
- [x] Don't push to last visited location when API language has been updated
- [x] Crashing when App starts (might be a react native issue)

More coming soon...

**Comment by HenryQuan** [comment]
This is quite old and outdated so I am closing this for now.
