### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/WoWs-Info-Re#31]
# Typescript
Everything will be rewritten in TypeScript. It means lots of work to do but this time, you can design first and then write code based on what you already have. 

## UI redesign
- [ ] Customisable home screen
- [ ] Split IOS and Android UI
- [ ] Support tablets (larger screens)
- [ ] Better UWP and Mac support

## TODO
- [ ] Everything data related will be stored inside `data`
- [ ] Personal Rating related will be stored inside `rating`
- [ ] All components will implement `WoWsInfoComponent`
- [ ] Group all `utils` together
- [ ] Think about what features to add in future updates
- [ ] Think about tablet related UI (1 : 2)
- [ ] Rewrite some classes (too messy now)
- [ ] Props will have their own classes (so pass an object to another screen)

*There shouldn't be any logic outside these classes*

### WoWsInfoData
- Default value for everything
- Get data from local storage
- Methods for getting and update value
- Safe storage
- Singeleton pattern

### WoWsData
- Checking version update
- Download data from WarGaming API and this repo

### PlayerData
- Singleton
- PlayerAchievementData
- PlayerShipData
- PlayerRankData

There should only be one player at a time so there are methods to set data and clear all saved data to null. This class will also do some basic calculation so UI is simply render what's being return from this class. *UI should only render and take care of different situations*

### WoWsInfoComponent
- isProFeature: boolean 

### CommonProps
- showBack?: boolean
- showProBanner?: boolean

### Support Tablet???
- WoWsInfo -> Mobile and Tablet

### Util
- Static functions in one class

### Rating
- Calculate personal rating depend on data

**Comment by HenryQuan** [comment]
Outdated because I am moving to Flutter.
